name: oracle_digital_internship
description: "Oracle Digital Internship Project by Amir Asakeev (ho1yspirt)"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # network
  dio: 5.3.3
  jwt_decoder: 2.0.1

  # state manager
  bloc: 8.1.2
  flutter_bloc: 8.1.3

  # internal
  logger: 2.0.2+1
  equatable: 2.0.5
  go_router: 12.0.1
  flutter_displaymode: 0.6.0

  # storage
  flutter_secure_storage: 9.0.0
  shared_preferences: 2.2.2

  # localization
  intl: 0.18.1
  flutter_localizations: 
    sdk: flutter

  # graphics and ui
  flutter_svg: 2.0.7
  cupertino_icons: 1.0.6
  cached_network_image: 3.3.0
  flutter_staggered_grid_view: 0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/comfortaa/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/comfortaa/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/comfortaa/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/comfortaa/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/comfortaa/Comfortaa-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
    

flutter_intl:
  enabled: true
  arb_dir: lib/src/core/localization/l10n
  output_dir: lib/src/core/localization/generated
